### ISSUE TITLE
Unable to connect to server after application runs for a day

### ISSUE THREAD

**Issue by salmanqureshi-olr** [KiboSoftware/nextjs-storefront#259]
We have been running the [nextjs](https://github.com/KiboSoftware/nextjs-builderio-starter-storefront-demos)
application and looking to build on it. However we have found an issue when running it over a period of time.
If we leave it running for more than an hour, the access token is successfully refreshed. However if we leave it running for over 12 hours, we get errors from the Kibo backend of the form:

{
    "items": [
        {
            "applicationName": "ReverseProxy",
            "errorCode": "UNAUTHORIZED",
            "message": "You are Unauthorized to perform the attempted operation.  https://t39369-s62243.sandbox.mozu.com/graphql IDX12741: JWT: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]' must have three segments (JWS) or five segments (JWE).",
            "additionalErrorData": [
                {
                    "name": "OperationName",
                    "value": "https://t39369-s62243.sandbox.mozu.com/graphql"
                }
            ]
        }
    ],
    "exceptionDetail": {
        "type": "Mozu.Core.Exceptions.VaeUnAuthorizedException",
        "message": "You are Unauthorized to perform the attempted operation.  https://t39369-s62243.sandbox.mozu.com/graphql IDX12741: JWT: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]' must have three segments (JWS) or five segments (JWE).",
        "source": "Mozu.ReverseProxy",
        "targetSite": "Void Validate(Mozu.ReverseProxy.ProxyRequest)",
        "stackTrace": "   at Mozu.ReverseProxy.RequestValidators.JwtInValidator.Validate(ProxyRequest request) in /src/Mozu.ReverseProxy/RequestValidators/JwtValidator.cs:line 93\n   at Mozu.ReverseProxy.RequestHandlers.RequestHandler.HandleAsync(ProxyRequest request) in /src/Mozu.ReverseProxy/RequestHandlers/RequestHandler.cs:line 165"
    }
}
with input requests such as
/api/graphql
and any query e.g.
  query getUser {
    customerAccount: getCurrentAccount {
      id
      userId
      firstName
      lastName
      emailAddress
      userName
      isAnonymous
    }
  }

**Comment by salmanqureshi-olr** [comment]
Also note that if we rebuild the app (npm run build) and restart (npm run start) the error disappears for another few hours.

**Comment by salmanqureshi-olr** [comment]
Here are the logs from when the connection was refused..

`Oct 09 16:51:53 opokiboacceleratorref01.olrretail.com start.sh[1209079]: Warning: data for page "/" is 296 kB which exceeds the threshold of 128 kB, this amount of data ca>Oct 09 16:51:53 opokiboacceleratorref01.olrretail.com start.sh[1209079]: See more info here: https://nextjs.org/docs/messages/large-page-data                               Oct 09 21:06:03 opokiboacceleratorref01.olrretail.com start.sh[1209079]: set auth                                                                                           Oct 09 21:06:04 opokiboacceleratorref01.olrretail.com start.sh[1209079]: set auth                                                                                           Oct 09 21:06:04 opokiboacceleratorref01.olrretail.com start.sh[1209079]: set auth                                                                                           Oct 09 21:06:04 opokiboacceleratorref01.olrretail.com start.sh[1209079]: set auth                                                                                           Oct 09 21:06:05 opokiboacceleratorref01.olrretail.com start.sh[1209079]: Warning: data for page "/" is 296 kB which exceeds the threshold of 128 kB, this amount of data ca>Oct 09 21:06:05 opokiboacceleratorref01.olrretail.com start.sh[1209079]: See more info here: https://nextjs.org/docs/messages/large-page-data                               Oct 10 07:18:24 opokiboacceleratorref01.olrretail.com start.sh[1209079]: set auth                                                                                           Oct 10 07:18:25 opokiboacceleratorref01.olrretail.com start.sh[1209079]: TypeError: Cannot read properties of undefined (reading 'length')                                  Oct 10 07:18:25 opokiboacceleratorref01.olrretail.com start.sh[1209079]:     at getCategoryTree (/opt/kibo-accelerator/code/.next/server/chunks/7088.js:117:23)             Oct 10 07:18:25 opokiboacceleratorref01.olrretail.com start.sh[1209079]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)                  Oct 10 07:18:25 opokiboacceleratorref01.olrretail.com start.sh[1209079]:     at async getStaticProps (/opt/kibo-accelerator/code/.next/server/pages/index.js:948:28)        `

**Comment by kibo-kevinwatts** [comment]
Thanks, looking into it

**Comment by salmanqureshi-olr** [comment]
Thank you..at the moment we are restarting the built application daily to get around this so it is blocking a proper environmental deploy.

**Comment by salmanqureshi-olr** [comment]
We are using the https://github.com/KiboSoftware/nextjs-builderio-starter-storefront-demos repo
It is built on this package, therefore raising it here (the one above has issues disabled)
